---
collections:
  - name: ansible.netcommon
    version: ">=2.0.0"
  - name: community.network
    version: ">=3.0.0"

# Note: Using generic network modules for Huawei devices
# Connection: network_cli
# Modules: cli_command, cli_config
