---
collections:
  - name: huawei.vrp
    version: ">=1.0.0"
  - name: ansible.netcommon
    version: ">=2.0.0"
  - name: community.network
    version: ">=3.0.0"

# Note: Using huawei.vrp instead of huawei.vrrp
# huawei.vrp is the correct collection for Huawei VRP devices
