---
collections:
  - name: huawei.vrrp
    version: ">=1.0.0"
  - name: ansible.netcommon
    version: ">=2.0.0"
  - name: community.network
    version: ">=3.0.0"

# Note: External roles removed as they don't exist
# Use built-in Ansible modules for backup and verification
